# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/11178f69-99a0-46bb-84e2-f2d579a2c599";
      fsType = "btrfs";
      options = [ "subvol=@" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/235A-CEF3";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/11178f69-99a0-46bb-84e2-f2d579a2c599";
      fsType = "btrfs";
      options = [ "subvol=@home" ];
    };

  fileSystems."/vms" =
    { device = "/dev/disk/by-uuid/11178f69-99a0-46bb-84e2-f2d579a2c599";
      fsType = "btrfs";
      options = [ "subvol=@vms" ];
    };

  fileSystems."/experiments" =
    { device = "/dev/disk/by-uuid/11178f69-99a0-46bb-84e2-f2d579a2c599";
      fsType = "btrfs";
      options = [ "subvol=@experiments" ];
    };

  fileSystems."/extra0" =
    { device = "/dev/disk/by-uuid/11178f69-99a0-46bb-84e2-f2d579a2c599";
      fsType = "btrfs";
      options = [ "subvol=@extra0" ];
    };

  fileSystems."/extra1" =
    { device = "/dev/disk/by-uuid/11178f69-99a0-46bb-84e2-f2d579a2c599";
      fsType = "btrfs";
      options = [ "subvol=@extra1" ];
    };

  fileSystems."/extra2" =
    { device = "/dev/disk/by-uuid/11178f69-99a0-46bb-84e2-f2d579a2c599";
      fsType = "btrfs";
      options = [ "subvol=@extra2" ];
    };

  fileSystems."/c" =
    { device = "/dev/disk/by-uuid/11178f69-99a0-46bb-84e2-f2d579a2c599";
      fsType = "btrfs";
      options = [ "subvol=@c" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/24412e02-60a9-44fc-8d53-0d1ec4cc9db7"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlo1.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
