#!/usr/bin/env bash
set -euo pipefail

if [ "$#" -eq 0 ]; then
  echo "Usage: ns <commit message>" >&2
  exit 1
fi

git -C /etc/nixos add -A
git -C /etc/nixos commit -m "$*"
git -C /etc/nixos push
sudo nixos-rebuild switch --flake /etc/nixos#alexhp
